# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  - group:  api-list-dev
steps:
- task: CmdLine@2
  inputs:
    script: | 
        echo TENANT_ID=$(TENANT_ID) > .env 
        echo CLIENT_ID=$(CLIENT_ID) >> .env
        echo CLIENT_SECRET=$(CLIENT_SECRET) >> .env
        echo TENANT_URL=$(TENANT_URL) >> .env
        echo SCOPE=$(SCOPE) >> .env
  displayName: 'Setting environment variables'
- task: NodeTool@0
  inputs:
    versionSpec: '16.16.0'
  displayName: 'Install Node.js'
- script: |
    npm install -g @nestjs/cli
  displayName: 'npm install cli'
- script: |
    npm install
  displayName: 'npm install'
- script: |
    npm run build
  displayName: 'npm build'
- task: CopyFiles@2
  inputs:
    Contents: '.env'
    TargetFolder: 'dist'                
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
  inputs:
   targetPath: '$(System.ArtifactsDirectory)'
   ArtifactName: 'drop'    